CREATE TABLE GameModeItem(
	GameModeItemId INT PRIMARY KEY,
	GamemodeID INT,
	HeroId INT,
	Kills INT,
	Assists INT,
	Revives INT,
	BestSquad INT,
	Wins INT,
	Losses INT,
	Mvp INT,
	Matches INT,
	SectorDefend INT,
	ObjectivesArmed INT,
	ObjectivesDisarmed INT,
	ObjectivesDefended INT,
	ObjectivesDestroyed INT,
	ObjetiveTime INT,
	KPM DECIMAL(10,2),
	WinPercent DECIMAL(10,2),
	SecondsPlayed INT,
	CONSTRAINT fk_GameModeItem_GamemodeID FOREIGN KEY (GamemodeID) REFERENCES Gamemode(GamemodeID),
	CONSTRAINT fk_GameModeItem_HeroId FOREIGN KEY (HeroId) REFERENCES Hero(HeroId)
);