CREATE TABLE HeroOverView (
    HeroOverViewId INT IDENTITY(1,1) PRIMARY KEY,
    HeroId INT,
    BestClass VARCHAR(20),
    HumanPercentage DECIMAL(10,2),
    Kills INT,
    Deaths INT,
    Wins INT,
    Losses INT,
    KillsPerMinute DECIMAL(10,2),
    DamagePerMinute DECIMAL(10,2),
	KillsPerMatch DECIMAL(10,2),
	DamagePerMatch DECIMAL(10,2),
	HeadShots INT,
	WinPercent DECIMAL(10,2),
	HeadShotrate DECIMAL(10,2),
	KillDeath DECIMAL(10,2),
	InfantryKillDeath DECIMAL(10,2),
	Damage INT,
	TimePlayed VARCHAR(30),
	Accuracy DECIMAL(10,2),
	Revives INT,
	Heals INT,
	Resupplies INT,
	Repairs INT,
	SquadmateRevive INT,
	SquadmateRespawn INT,
	ThrownThrowables INT,
	GadgetsDestoyed INT,
	CallIns INT,
	PlayerTakeDowns INT,
	MatchesPlayed INT,
	SecondsPlayed INT,
	BestSquad INT,
	TeammatesSupported INT,
	SaviorKills INT,
	ShotsFired INT,
	ShotsHit INT,
	KillAssists INT,
	VehiclesDestroyed INT,
    EnemiesSpotted INT,
    Mvp INT,
    CONSTRAINT fk_HeroOverView_HeroId FOREIGN KEY (HeroId) REFERENCES Hero(HeroId)
);
