//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GadgetItem
    {
        public int GadgetItemId { get; set; }
        public Nullable<int> GadgetId { get; set; }
        public Nullable<int> HeroId { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> Spawns { get; set; }
        public Nullable<int> Damage { get; set; }
        public Nullable<int> Uses { get; set; }
        public Nullable<int> Multikills { get; set; }
        public Nullable<int> VehiclesDestroyedWith { get; set; }
        public Nullable<decimal> KPM { get; set; }
        public Nullable<decimal> DPM { get; set; }
        public Nullable<int> SecondsPlayed { get; set; }
    
        public virtual Gadget Gadget { get; set; }
        public virtual Hero Hero { get; set; }
    }
}
