//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GObject()
        {
            this.GObjectItem = new HashSet<GObjectItem>();
        }
    
        public int GObjectID { get; set; }
        public Nullable<int> Herold { get; set; }
        public Nullable<int> Armed { get; set; }
        public Nullable<int> Captured { get; set; }
        public Nullable<int> Neutralized { get; set; }
        public Nullable<int> Destroyed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GObjectItem> GObjectItem { get; set; }
    }
}
