//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GObjectItem
    {
        public int GObjectItemId { get; set; }
        public Nullable<int> HeroId { get; set; }
        public Nullable<int> GObjectID { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Attacked { get; set; }
        public Nullable<int> Defended { get; set; }
    
        public virtual GObject GObject { get; set; }
        public virtual Hero Hero { get; set; }
    }
}
