//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroOverView
    {
        public int HeroOverViewId { get; set; }
        public Nullable<int> HeroId { get; set; }
        public string BestClass { get; set; }
        public Nullable<decimal> HumanPercentage { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> Deaths { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<decimal> KillsPerMinute { get; set; }
        public Nullable<decimal> DamagePerMinute { get; set; }
        public Nullable<decimal> KillsPerMatch { get; set; }
        public Nullable<decimal> DamagePerMatch { get; set; }
        public Nullable<int> HeadShots { get; set; }
        public Nullable<decimal> WinPercent { get; set; }
        public Nullable<decimal> HeadShotrate { get; set; }
        public Nullable<decimal> KillDeath { get; set; }
        public Nullable<decimal> InfantryKillDeath { get; set; }
        public Nullable<int> Damage { get; set; }
        public string TimePlayed { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public Nullable<int> Revives { get; set; }
        public Nullable<int> Heals { get; set; }
        public Nullable<int> Resupplies { get; set; }
        public Nullable<int> Repairs { get; set; }
        public Nullable<int> SquadmateRevive { get; set; }
        public Nullable<int> SquadmateRespawn { get; set; }
        public Nullable<int> ThrownThrowables { get; set; }
        public Nullable<int> GadgetsDestoyed { get; set; }
        public Nullable<int> CallIns { get; set; }
        public Nullable<int> PlayerTakeDowns { get; set; }
        public Nullable<int> MatchesPlayed { get; set; }
        public Nullable<int> SecondsPlayed { get; set; }
        public Nullable<int> BestSquad { get; set; }
        public Nullable<int> TeammatesSupported { get; set; }
        public Nullable<int> SaviorKills { get; set; }
        public Nullable<int> ShotsFired { get; set; }
        public Nullable<int> ShotsHit { get; set; }
        public Nullable<int> KillAssists { get; set; }
        public Nullable<int> VehiclesDestroyed { get; set; }
        public Nullable<int> EnemiesSpotted { get; set; }
        public Nullable<int> Mvp { get; set; }
    
        public virtual Hero Hero { get; set; }
    }
}
