//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapItem
    {
        public int MapItemId { get; set; }
        public int MapId { get; set; }
        public int HeroId { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<int> Matches { get; set; }
        public Nullable<decimal> WinPercent { get; set; }
        public Nullable<int> SecondsPlayed { get; set; }
    
        public virtual Hero Hero { get; set; }
        public virtual Map Map { get; set; }
    }
}
