//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ribbon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ribbon()
        {
            this.RibbonItem = new HashSet<RibbonItem>();
        }
    
        public int RibbonID { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Squad { get; set; }
        public Nullable<int> Combat { get; set; }
        public Nullable<int> Intel { get; set; }
        public Nullable<int> Objective { get; set; }
        public Nullable<int> Support { get; set; }
        public Nullable<int> HeroId { get; set; }
    
        public virtual Hero Hero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RibbonItem> RibbonItem { get; set; }
    }
}
