//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RibbonItem
    {
        public int RibbonItemID { get; set; }
        public Nullable<int> RibbonID { get; set; }
        public Nullable<int> HeroId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Hero Hero { get; set; }
        public virtual Ribbon Ribbon { get; set; }
    }
}
