//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialist()
        {
            this.SpecialistItem = new HashSet<SpecialistItem>();
        }
    
        public int SpecialistID { get; set; }
        public string ClassName { get; set; }
        public string CharacterName { get; set; }
        public string StatName { get; set; }
        public string Image { get; set; }
        public string AvatarImage1 { get; set; }
        public string AvatarImage2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialistItem> SpecialistItem { get; set; }
    }
}
