//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialistItem
    {
        public int SpecialistItemID { get; set; }
        public Nullable<int> SpecialistID { get; set; }
        public Nullable<int> HeroId { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> Deaths { get; set; }
        public Nullable<decimal> KMP { get; set; }
        public Nullable<int> Spawns { get; set; }
        public Nullable<decimal> KillDeath { get; set; }
        public Nullable<int> Revives { get; set; }
        public Nullable<int> Assists { get; set; }
        public Nullable<int> HazardZoneStreaks { get; set; }
        public Nullable<int> SecondsPlayed { get; set; }
    
        public virtual Hero Hero { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
