//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleItem
    {
        public int VehicleItemId { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> HeroId { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> Damage { get; set; }
        public Nullable<int> Roadkills { get; set; }
        public Nullable<int> Spawns { get; set; }
        public Nullable<int> DriverAssists { get; set; }
        public Nullable<int> PassengerAssists { get; set; }
        public Nullable<int> Multikills { get; set; }
        public Nullable<int> DistanceTraveled { get; set; }
        public Nullable<decimal> KillsPerMinute { get; set; }
        public Nullable<int> VehiclesDestroyedWith { get; set; }
        public Nullable<int> Assists { get; set; }
        public Nullable<int> Callins { get; set; }
        public Nullable<int> DamageTo { get; set; }
        public Nullable<int> Destroyed { get; set; }
        public Nullable<int> Timeln { get; set; }
    
        public virtual Hero Hero { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
