//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEDATAHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleGroup
    {
        public int VehicleGroupID { get; set; }
        public Nullable<int> HeroId { get; set; }
        public string Type { get; set; }
        public string VehicleName { get; set; }
        public string Image { get; set; }
        public string Id { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> Damage { get; set; }
        public Nullable<int> Roadkills { get; set; }
        public Nullable<int> Spawns { get; set; }
        public Nullable<int> DriverAssists { get; set; }
        public Nullable<int> PassengerAssists { get; set; }
        public Nullable<int> MultiKills { get; set; }
        public Nullable<decimal> DistanceTraveled { get; set; }
        public Nullable<int> KillsPerMinute { get; set; }
        public Nullable<int> VehiclesDestroyedWith { get; set; }
        public Nullable<int> Assists { get; set; }
        public Nullable<int> CallIns { get; set; }
        public Nullable<int> DamageTo { get; set; }
        public Nullable<int> Destroyed { get; set; }
        public Nullable<int> Timeln { get; set; }
    
        public virtual Hero Hero { get; set; }
    }
}
